[package]
name = "my_project_parser_rogue_druid_on_hearthstone_matt_piper_formal_bound_duo_2025_enjoyer"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A brief description"
[dependencies]
peg = "0.8.4"